myblog/urls.py
# from django.conf.urls import url
# from . import views
#
# urlpatterns = [
#     url(r'^(?P<blog_id>[0-9]+)/$', views.post, name="blog")
# ]

pytdjangoblog/urls.py
from django.conf.urls import url
from django.contrib import admin

from myblog.views import hello, current_time
from books import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/$', hello),
    url(r'^time/$', current_time),

    url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),

    url(r'^contact/$', views.contact),
]

books/models.py
from django.db import models

# Create your models here.

class Publisher (models.Model) :
    """data for Publisher ."""
    name            = models.CharField  (max_length = 30)
    address         = models.CharField  (max_length = 50)
    city            = models.CharField  (max_length = 20)
    state_provice   = models.CharField  (max_length = 20)
    country         = models.CharField  (max_length = 20)
    website         = models.URLField   ()

    def __str__(self):
        "return String Object"
        return self.name

    class Meta:
        ordering = ['name']


class Author (models.Model) :
    """data for Author ."""
    first_name      = models.CharField  (max_length = 15)
    last_name       = models.CharField  (max_length = 15)
    email           = models.EmailField (blank      = True, verbose_name = 'e-mail')

    def __str__(self):
        "return String Object"
        return u'%s %s' % (self.first_name, self.last_name)

    class Meta :
        ordering = ['first_name', 'last_name']



class Book (models.Model):
    """data for Book ."""
    title               = models.CharField  (max_length = 100)
    publication_date    = models.DateField  (blank= True, null=True)

    authors             = models.ManyToManyField    (Author)
    publisher           = models.ForeignKey         (Publisher)

    def __str__(self):
        "return String Object"
        return self.title

    class Meta :
        ordering = ['publication_date']

myblog/models.py
from django.db import models

# Create your models here.
# class Post(models.Model):
#     title   = models.CharField  (max_length = 200)
#     content = models.Textarea   (max_length = 2000)
#

books/forms.py
from django import forms

class ContactForm(forms.Form) :
    # defult to all forms is required
    subject = forms.CharField(max_length=100)
    email   = forms.EmailField(required=False, label="Your Email")
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self) :
        message = self.cleaned_data['message']
        num_words = len(message.split() )
        if num_words < 4 :
            raise forms.ValidationError ("Not enough words!")

        return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

from books.models import Book
from books.forms import ContactForm

def search_form (request) :
    return render(request, 'search_form.html')

def search (request) :
    errors  = []
    if 'q' in request.GET :
        q = request.GET['q']
        if not 'q' :
            errors.append("Please enter a saecrh term")
        elif len(q) > 20 :
            errors.append("Plese submit search term 20 characters or shorter")
        else :
            books = Book.objects.filter(title__icontains=q)
            return render (request, 'search_form.html', {'books' : books, 'query' : q })

    return render(request, 'search_form.html', {'errors' : errors})


def contact(request) :
    if request.method == "POST" :
        form = ContactForm(request.POST)
        if form.is_valid() :
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'example@email.com'),
                ['admin@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else :
        form = ContactForm(
            initial  ={'subject': 'I love your site!' }
        )

    return render(request, 'contact_form.html', {'form' : form})

myblog/views.py
# from django.template.loader import get_template
# from django.template import Context
# from django.http import HttpResponse

from django.shortcuts import render

import datetime

# Create your views here.
def hello(request):
    return HttpResponse('hello world')


def current_time(request):
    now = datetime.datetime.now()

    return render(request, 'current_datetime.html', {'current_date': now})

    # html = "<html><body>It's now %s</body></html>" % now

    # t = get_template('current_datetime.html')
    # html = t.render(Context({'current_date' : now}))
    # return HttpResponse(html)

books/templates/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Contact Us</title>
</head>
<body>
   <style type="text/css">
      ul.errorlist {
           margin: 0;
           padding: 0;
      }
      .errorlist li {
           background-color: red;
           color: white;
           display: block;
           font-size: 10px;
           margin: 0 0 3px;
           padding: 4px 5px;
      }
   </style>

   <h1>contact form</h1>

   {% if form.errors %}
      <p style="color: red">
         Please corect the error {{form.errors|pluralize}} below
      </p>
   {% endif %}

   <form action="" method="post">
      <div class="field">
         {{ form.subject.errors }}
         <label for="id_subject">Subject : </label>
         {{ form.subject }}
      </div>

      <div class="field">
         {{ form.email.errors }}
         <label for="id_email">Email : </label>
         {{ form.email }}
      </div>
      <div class="field">
         {{ form.message.errors }}
         <label for="id_message">Message : </label>
         {{ form.message }}
      </div>

      {% csrf_token %}
      <input type="submit" value="submit">
   </form>
</body>
</html>


<!-- <div class="field{% if form.message.errors %} errors{% endif %}">
    {% if form.message.errors %}
        <ul>
        {% for error in form.message.errors %}
            <li><strong>{{ error }}</strong></li>
        {% endfor %}
        </ul>
    {% endif %}
    <label for="id_message">Message:</label>
    {{ form.message }}
</div> -->

books/templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Search</title>
</head>
<body>

   {% if errors %}
      <ul>
         {% for error in errors %}
         <li>{{ error }}</li>
         {% endfor %}
      </ul>
   {% endif %}

   <form action="/search/" method="get">
      <input type="text" name="q">
      <input type="submit" value="Search">
   </form>

</body>
</html>

books/templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Book search</title>
</head>
<body>


   <p>You search for : <strong> {{ query }} </strong></p>

   {% if books %}
      <p>Found {{ books|length }} book {{ books|pluralize }}</p>
         <ul>
            {% for book in books %}
            <li> {{ book.title }} </li>
            {% endfor %}
         </ul>
   {% else %}
      <p>No books matched your search criteria</p>
   {% endif %}

</body>
</html>

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">

   <title>{% block title %} {% endblock %}</title>

</head>
<body>
   <h1>timestamp</h1>
   <!-- <p>it's now {{ current_date }}</p> -->
   {% block content %} {% endblock %}

   {% block footer %}
   <p>thanks for visiting</p>
   {% endblock %}
</body>
</html>

myblog/templates/current_datetime.html
{% extends 'base.html' %}

{% block title %} Current time {% endblock %}
{% block content %}
    <p> it's now {{ current_date }} </p>
{% endblock %}